import type { AccountLivenessModel } from "./accounts";
import type { UsageLimitDefaultRanges } from "./usage";
export type AppSettings = {
  management_site_base_url: string;
  management_site_port: number | null;
  management_site_base_url_source: string;
  management_site_x_api_key_set: boolean;
  management_site_x_api_key_hint: string | null;
  management_site_auto_recover_state: boolean;
  automation_paused: boolean;
  oauth_account_sync_enabled: boolean;
  oauth_login_mode: "protocol" | "browser";
  oauth_stop_on_phone_verification: boolean;
  recovery_enabled: boolean;
  monitor_interval_seconds: number;
  usage_refresh_enabled: boolean;
  usage_refresh_interval_seconds: number;
  usage_refresh_max_concurrency: number;
  api_key_account_sync_enabled: boolean;
  api_key_account_sync_interval_seconds: number;
  upstream_sync_enabled: boolean;
  upstream_sync_interval_seconds: number;
  upstream_sync_max_concurrency: number;
  upstream_rate_sync_enabled: boolean;
  upstream_priority_sync_enabled: boolean;
  manual_upstream_sync_rate_enabled: boolean;
  manual_upstream_sync_priority_enabled: boolean;
  manual_upstream_sync_upstream_health_enabled: boolean;
  manual_upstream_monitor_sync_enabled: boolean;
  manual_upstream_sync_account_availability_enabled: boolean;
  manual_upstream_sync_balance_guard_enabled: boolean;
  manual_upstream_sync_rate_pause_enabled: boolean;
  api_key_auto_disable_on_upstream_unavailable: boolean;
  api_key_auto_pause_on_negative_balance_enabled: boolean;
  api_account_auto_pause_on_upstream_monitor_unavailable_enabled: boolean;
  api_key_availability_all_tests_must_succeed: boolean;
  upstream_monitor_auto_probe_enabled: boolean;
  account_model_whitelist_sync_enabled: boolean;
  account_model_whitelist_sync_interval_seconds: number;
  account_model_whitelist_sync_each_time: boolean;
  upstream_monitor_fallback_without_monitor_enabled: boolean;
  upstream_monitor_fallback_test_models: string[];
  upstream_monitor_fallback_test_model: string;
  upstream_monitor_fallback_test_attempts: number;
  upstream_monitor_recovery_test_attempts: number;
  upstream_monitor_test_attempt_interval_seconds: number;
  available_test_models: AccountLivenessModel[];
  upstream_negative_balance_basis: "wallet" | "recharge_adjusted";
  upstream_balance_pause_threshold: number;
  show_stale_negative_balance_alert: boolean;
  priority_assign_disabled_api_key_accounts: boolean;
  priority_share_same_upstream_actual_multiplier: boolean;
  upstream_rate_log_retention_days: number;
  change_log_page_size: number;
  change_log_page_size_options: number[];
  /** Number of days to keep per-day upstream usage detail. Lifetime totals are retained separately. */
  upstream_usage_data_retention_days?: number;
  discord_bot_notifications_enabled: boolean;
  discord_bot_token_set: boolean;
  discord_bot_token_hint: string | null;
  discord_bot_channel_id: string;
  notify_oauth_account_disabled: boolean;
  notify_account_enabled: boolean;
  notify_api_key_rate_changed: boolean;
  notify_upstream_group_changed: boolean;
  notify_upstream_balance_low: boolean;
  notify_upstream_token_invalid: boolean;
  usage_limit_sample_five_hour_threshold_percent: number;
  usage_limit_sample_seven_day_threshold_percent: number;
  usage_limit_default_ranges: UsageLimitDefaultRanges;
  refresh_max_concurrency: number;
  protocol_refresh_max_concurrency: number;
  browser_refresh_max_concurrency: number;
  browser_min_available_memory_mb: number;
  subscription_refresh_batch_size: number;
  subscription_refresh_max_concurrency: number;
  account_liveness_max_concurrency: number;
  last_scan_at: string | null;
  last_scan_status: string | null;
  last_scan_message: string | null;
  display_timezone: string;
  site_name: string;
  site_logo_url: string | null;
  site_logo_updated_at: string | null;
};

export type AppSettingsUpdate = {
  management_site_base_url?: string;
  management_site_port?: number;
  management_site_x_api_key?: string;
  clear_management_site_x_api_key?: boolean;
  confirm_management_site_credential_rebind?: boolean;
  management_site_auto_recover_state?: boolean;
  automation_paused?: boolean;
  oauth_account_sync_enabled?: boolean;
  oauth_login_mode?: "protocol" | "browser";
  oauth_stop_on_phone_verification?: boolean;
  recovery_enabled?: boolean;
  monitor_interval_seconds?: number;
  usage_refresh_enabled?: boolean;
  usage_refresh_interval_seconds?: number;
  usage_refresh_max_concurrency?: number;
  api_key_account_sync_enabled?: boolean;
  api_key_account_sync_interval_seconds?: number;
  upstream_sync_enabled?: boolean;
  upstream_sync_interval_seconds?: number;
  upstream_sync_max_concurrency?: number;
  upstream_rate_sync_enabled?: boolean;
  upstream_priority_sync_enabled?: boolean;
  manual_upstream_sync_rate_enabled?: boolean;
  manual_upstream_sync_priority_enabled?: boolean;
  manual_upstream_sync_upstream_health_enabled?: boolean;
  manual_upstream_monitor_sync_enabled?: boolean;
  manual_upstream_sync_account_availability_enabled?: boolean;
  manual_upstream_sync_balance_guard_enabled?: boolean;
  manual_upstream_sync_rate_pause_enabled?: boolean;
  api_key_auto_disable_on_upstream_unavailable?: boolean;
  api_key_auto_pause_on_negative_balance_enabled?: boolean;
  api_account_auto_pause_on_upstream_monitor_unavailable_enabled?: boolean;
  api_key_availability_all_tests_must_succeed?: boolean;
  upstream_monitor_auto_probe_enabled?: boolean;
  account_model_whitelist_sync_enabled?: boolean;
  account_model_whitelist_sync_interval_seconds?: number;
  account_model_whitelist_sync_each_time?: boolean;
  upstream_monitor_fallback_without_monitor_enabled?: boolean;
  upstream_monitor_fallback_test_models?: string[];
  upstream_monitor_fallback_test_model?: string;
  upstream_monitor_fallback_test_attempts?: number;
  upstream_monitor_recovery_test_attempts?: number;
  upstream_monitor_test_attempt_interval_seconds?: number;
  upstream_negative_balance_basis?: "wallet" | "recharge_adjusted";
  upstream_balance_pause_threshold?: number;
  show_stale_negative_balance_alert?: boolean;
  priority_assign_disabled_api_key_accounts?: boolean;
  priority_share_same_upstream_actual_multiplier?: boolean;
  upstream_rate_log_retention_days?: number;
  change_log_page_size?: number;
  change_log_page_size_options?: number[];
  upstream_usage_data_retention_days?: number;
  discord_bot_notifications_enabled?: boolean;
  discord_bot_token?: string;
  clear_discord_bot_token?: boolean;
  discord_bot_channel_id?: string;
  notify_oauth_account_disabled?: boolean;
  notify_account_enabled?: boolean;
  notify_api_key_rate_changed?: boolean;
  notify_upstream_group_changed?: boolean;
  notify_upstream_balance_low?: boolean;
  notify_upstream_token_invalid?: boolean;
  usage_limit_sample_five_hour_threshold_percent?: number;
  usage_limit_sample_seven_day_threshold_percent?: number;
  usage_limit_default_ranges?: UsageLimitDefaultRanges;
  refresh_max_concurrency?: number;
  protocol_refresh_max_concurrency?: number;
  browser_refresh_max_concurrency?: number;
  browser_min_available_memory_mb?: number;
  subscription_refresh_batch_size?: number;
  subscription_refresh_max_concurrency?: number;
  account_liveness_max_concurrency?: number;
  display_timezone?: string;
  site_name?: string;
};

export type SiteLogoUpdateResult = {
  site_logo_url: string | null;
  site_logo_updated_at: string | null;
  message?: string;
};

export type ManagementSiteScanResult = {
  found: boolean;
  base_url: string | null;
  port: number | null;
  status: string;
  message: string;
  checked_ports: number[];
  applied: boolean;
};
export { automationDurationDisplayValue, automationDurationSecondsValue, automationDurationUnits, preferredAutomationDurationUnit } from "../automationDuration";

